[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "databases[aiosqlite]>=0.9.0",
    "platformdirs>=4.3.6",
    "pyautogui>=0.9.54",
    "pytest>=8.3.3",
]
