CREATE "keypress" IF NOT EXISTS ("id" PRIMARY KEY AUTOINCREMENT,"event_key" INTEGER NOT NULL,"event_value" INTEGER NOT NULL,"time" REAL NOT NULL)
CREATE "mousepress" IF NOT EXISTS ("id" PRIMARY KEY AUTOINCREMENT,"event_key" INTEGER NOT NULL,"event_value" INTEGER NOT NULL,"time" REAL NOT NULL)
CREATE "screens" IF NOT EXISTS ("id","key","time")
CREATE "windows_title" IF NOT EXISTS ("id" PRIMARY KEY AUTOINCREMENT,"title" TEXT NOT NULL,"time" REAL NOT NULL)
CREATE "screenshots" IF NOT EXISTS ("id" PRIMARY KEY AUTOINCREMENT,"filepath" TEXT NOT NULL,"time" REAL NOT NULL)

